"""Add pipeline configs table

Revision ID: 1a7b76fd3c80
Revises: 33c69bd8272b
Create Date: 2026-06-26 17:14:10.015222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a7b76fd3c80'
down_revision: Union[str, Sequence[str], None] = '33c69bd8272b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('enable_living_docs_update', sa.Boolean(), nullable=False),
    sa.Column('enable_editor_loop', sa.Boolean(), nullable=False),
    sa.Column('max_rewrite', sa.Integer(), nullable=False),
    sa.Column('readonly_docs', sa.JSON(), nullable=False),
    sa.Column('required_docs', sa.JSON(), nullable=False),
    sa.Column('enable_force_correction', sa.Boolean(), nullable=False),
    sa.Column('validation_before_editor', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_configs')
    # ### end Alembic commands ###
