"""add category to prompt_templates

Revision ID: 2bbc8d168d99
Revises: 8e5e1092ee6b
Create Date: 2026-06-24 14:56:03.477435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bbc8d168d99'
down_revision: Union[str, Sequence[str], None] = '8e5e1092ee6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_templates', sa.Column('category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_templates', 'category')
    # ### end Alembic commands ###
