"""add cascade delete

Revision ID: 2d0e08d9a7b2
Revises: 093b310b0795
Create Date: 2026-06-12 13:42:48.872922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0e08d9a7b2'
down_revision: Union[str, Sequence[str], None] = '093b310b0795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chapter_outlines_project_id_fkey'), 'chapter_outlines', type_='foreignkey')
    op.create_foreign_key(None, 'chapter_outlines', 'novels', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('chapters_novel_id_fkey'), 'chapters', type_='foreignkey')
    op.create_foreign_key(None, 'chapters', 'novels', ['novel_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('issue_summaries_project_id_fkey'), 'issue_summaries', type_='foreignkey')
    op.create_foreign_key(None, 'issue_summaries', 'novels', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('jobs_project_id_fkey'), 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'novels', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('living_doc_versions_project_id_fkey'), 'living_doc_versions', type_='foreignkey')
    op.create_foreign_key(None, 'living_doc_versions', 'novels', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('raw_issues_project_id_fkey'), 'raw_issues', type_='foreignkey')
    op.create_foreign_key(None, 'raw_issues', 'novels', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('vector_outbox_project_id_fkey'), 'vector_outbox', type_='foreignkey')
    op.create_foreign_key(None, 'vector_outbox', 'novels', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vector_outbox', type_='foreignkey')
    op.create_foreign_key(op.f('vector_outbox_project_id_fkey'), 'vector_outbox', 'novels', ['project_id'], ['id'])
    op.drop_constraint(None, 'raw_issues', type_='foreignkey')
    op.create_foreign_key(op.f('raw_issues_project_id_fkey'), 'raw_issues', 'novels', ['project_id'], ['id'])
    op.drop_constraint(None, 'living_doc_versions', type_='foreignkey')
    op.create_foreign_key(op.f('living_doc_versions_project_id_fkey'), 'living_doc_versions', 'novels', ['project_id'], ['id'])
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_project_id_fkey'), 'jobs', 'novels', ['project_id'], ['id'])
    op.drop_constraint(None, 'issue_summaries', type_='foreignkey')
    op.create_foreign_key(op.f('issue_summaries_project_id_fkey'), 'issue_summaries', 'novels', ['project_id'], ['id'])
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.create_foreign_key(op.f('chapters_novel_id_fkey'), 'chapters', 'novels', ['novel_id'], ['id'])
    op.drop_constraint(None, 'chapter_outlines', type_='foreignkey')
    op.create_foreign_key(op.f('chapter_outlines_project_id_fkey'), 'chapter_outlines', 'novels', ['project_id'], ['id'])
    # ### end Alembic commands ###
