"""add name_zh to pipeline_configs

Revision ID: 79d65d68f0f4
Revises: 1a7b76fd3c80
Create Date: 2026-06-26 17:30:28.142360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79d65d68f0f4'
down_revision: Union[str, Sequence[str], None] = '1a7b76fd3c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_configs', sa.Column('name_zh', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_configs', 'name_zh')
    # ### end Alembic commands ###
