"""Add temporal graph models

Revision ID: 8e5e1092ee6b
Revises: 7f8c3e5d4a21
Create Date: 2026-06-21 16:29:33.408577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e5e1092ee6b'
down_revision: Union[str, Sequence[str], None] = '7f8c3e5d4a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('source_node_id', sa.Uuid(), nullable=False),
    sa.Column('target_node_id', sa.Uuid(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('valid_from_chapter', sa.Integer(), nullable=False),
    sa.Column('valid_to_chapter', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('novels_reference_book_id_fkey', 'novels', type_='foreignkey')
    op.create_foreign_key(None, 'novels', 'novels', ['reference_book_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'novels', type_='foreignkey')
    op.create_foreign_key('novels_reference_book_id_fkey', 'novels', 'novels', ['reference_book_id'], ['id'])
    op.drop_table('graph_edges')
    op.drop_table('graph_nodes')
    # ### end Alembic commands ###
