"""add name_zh to prompt_templates

Revision ID: a59471799ea7
Revises: e71ac504ace1
Create Date: 2026-06-26 17:41:15.049801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a59471799ea7'
down_revision: Union[str, Sequence[str], None] = 'e71ac504ace1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_templates', sa.Column('name_zh', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_templates', 'name_zh')
    # ### end Alembic commands ###
