"""add novel_format to novel

Revision ID: a67ec1f3e3f7
Revises: 2bbc8d168d99
Create Date: 2026-06-24 15:03:03.325376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a67ec1f3e3f7'
down_revision: Union[str, Sequence[str], None] = '2bbc8d168d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('novels', sa.Column('novel_format', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('novels', 'novel_format')
    # ### end Alembic commands ###
