"""add system dict tables

Revision ID: e71ac504ace1
Revises: 79d65d68f0f4
Create Date: 2026-06-26 17:33:43.208813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e71ac504ace1'
down_revision: Union[str, Sequence[str], None] = '79d65d68f0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_doc_types',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name_zh', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_nodes',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name_zh', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_nodes')
    op.drop_table('system_doc_types')
    # ### end Alembic commands ###
