"""Shared constants for the character-card domain."""

CHARACTER_STORYLINE_MAIN = "main"
CHARACTER_FIRST_CHAPTER = 1

CHARACTER_STATUS_ACTIVE = "active"
CHARACTER_STATUS_DORMANT = "dormant"
CHARACTER_STATUS_DECEASED = "deceased"
CHARACTER_STATUS_RETIRED = "retired"
CHARACTER_STATUS_UNKNOWN = "unknown"
CHARACTER_STATUSES = (
    CHARACTER_STATUS_ACTIVE,
    CHARACTER_STATUS_DORMANT,
    CHARACTER_STATUS_DECEASED,
    CHARACTER_STATUS_RETIRED,
)

CHARACTER_STATUS_ALIASES = {
    "active": CHARACTER_STATUS_ACTIVE,
    "alive": CHARACTER_STATUS_ACTIVE,
    "living": CHARACTER_STATUS_ACTIVE,
    "已找到": CHARACTER_STATUS_ACTIVE,
    "正常": CHARACTER_STATUS_ACTIVE,
    "dormant": CHARACTER_STATUS_DORMANT,
    "unknown": CHARACTER_STATUS_DORMANT,
    "missing": CHARACTER_STATUS_DORMANT,
    "失踪": CHARACTER_STATUS_DORMANT,
    "休眠": CHARACTER_STATUS_DORMANT,
    "deceased": CHARACTER_STATUS_DECEASED,
    "dead": CHARACTER_STATUS_DECEASED,
    "destroyed": CHARACTER_STATUS_DECEASED,
    "死亡": CHARACTER_STATUS_DECEASED,
    "已故": CHARACTER_STATUS_DECEASED,
    "已销毁": CHARACTER_STATUS_DECEASED,
    "retired": CHARACTER_STATUS_RETIRED,
    "退场": CHARACTER_STATUS_RETIRED,
}


def normalize_character_status(value: object) -> str | None:
    """Map model-facing status variants to the four persisted statuses."""
    if value is None:
        return None
    normalized = str(value).strip().lower()
    return CHARACTER_STATUS_ALIASES.get(normalized)

CHARACTER_IMPORTANCE_LOW = "low"
CHARACTER_IMPORTANCE_MEDIUM = "medium"
CHARACTER_IMPORTANCE_HIGH = "high"
CHARACTER_IMPORTANCES = (
    CHARACTER_IMPORTANCE_LOW,
    CHARACTER_IMPORTANCE_MEDIUM,
    CHARACTER_IMPORTANCE_HIGH,
)

CHARACTER_ARC_MAIN = "main"
CHARACTER_ARC_SIDE = "side"
CHARACTER_ARC_DEFAULT_TYPE = CHARACTER_ARC_MAIN
CHARACTER_ARC_TYPES = (CHARACTER_ARC_MAIN, CHARACTER_ARC_SIDE)
CHARACTER_ARC_NAME_KEYS = ("name", "title", "arc_name", "路线名称", "名称")
CHARACTER_ARC_MAIN_NAME = "主线成长路线"
CHARACTER_ARC_SIDE_NAME_PREFIX = "支线"
CHARACTER_ARC_SOURCE_CARD = "character_card"

CHARACTER_RELATIONSHIP_ACTIVE = "active"
CHARACTER_RELATIONSHIP_INACTIVE = "inactive"
CHARACTER_RELATIONSHIP_DEFAULT_TYPE = "相关"
CHARACTER_RELATIONSHIP_DEFAULT_STATUS = CHARACTER_RELATIONSHIP_ACTIVE
CHARACTER_ARC_DEFAULT_STATUS = CHARACTER_STATUS_ACTIVE

CHARACTER_CARD_SECTIONS = (
    "identity",
    "appearance",
    "personality",
    "background",
    "abilities",
    "speech_style",
    "behavior_patterns",
    "knowledge_boundary",
    "relationships",
    "growth_route",
    "main_arc",
    "side_arcs",
    "constraints",
)

CHARACTER_GENERATION_DEFAULT_IMPORTANCE = CHARACTER_IMPORTANCE_MEDIUM
CHARACTER_GENERATION_DEFAULT_STATUS = CHARACTER_STATUS_ACTIVE
CHARACTER_GENERATION_MAX_BATCH_SIZE = 30
CHARACTER_CONTEXT_MAX_MANIFESTS = 100
CHARACTER_CONTEXT_NO_PRIOR_CHAPTER = 0
CHARACTER_MANIFEST_SUMMARY_MAX_CHARS = 220
CHARACTER_CHAPTER_SOURCE_REF_TEMPLATE = "chapter:{chapter_index}"

# Chapter extraction has historically returned both Chinese-facing and
# internal English state keys. Normalize them before persisting a snapshot so
# a character cannot retain multiple values for the same fact.
CHARACTER_STATE_KEY_ALIASES = {
    "状态": "status",
    "当前状态": "status",
    "等级": "cultivation",
    "境界": "cultivation",
    "当前境界": "cultivation",
    "位置": "location",
    "当前地点": "location",
    "当前位置": "location",
    "current_location": "location",
    "目标": "goal",
    "当前目标": "goal",
    "计划": "plan",
    "身体状态": "condition",
    "健康状况": "condition",
    "当前情绪": "emotion",
    "心情": "emotion",
    "已知信息": "knowledge",
    "未完成事项": "open_threads",
    "章节": "chapter",
    "修炼进度": "cultivation_progress",
}

CHARACTER_BRANCH_STATUS_PENDING = "pending"
CHARACTER_BRANCH_STATUS_GENERATING = "generating"
CHARACTER_BRANCH_STATUS_DRAFT = "draft"
CHARACTER_BRANCH_STATUS_READY = "ready"
CHARACTER_BRANCH_STATUS_FAILED = "failed"
CHARACTER_BRANCH_STATUS_ARCHIVED = "archived"
CHARACTER_BRANCH_STATUSES = (
    CHARACTER_BRANCH_STATUS_PENDING,
    CHARACTER_BRANCH_STATUS_GENERATING,
    CHARACTER_BRANCH_STATUS_DRAFT,
    CHARACTER_BRANCH_STATUS_READY,
    CHARACTER_BRANCH_STATUS_FAILED,
    CHARACTER_BRANCH_STATUS_ARCHIVED,
)

CHARACTER_BRANCH_CHAPTER_STATUS_DRAFT = "draft"
CHARACTER_BRANCH_CHAPTER_STATUS_GENERATING = "generating"
CHARACTER_BRANCH_CHAPTER_STATUS_READY = "ready"
CHARACTER_BRANCH_CHAPTER_STATUS_FAILED = "failed"
CHARACTER_BRANCH_CHAPTER_STATUS_REVIEW = "review"
CHARACTER_BRANCH_CHAPTER_STATUSES = (
    CHARACTER_BRANCH_CHAPTER_STATUS_DRAFT,
    CHARACTER_BRANCH_CHAPTER_STATUS_GENERATING,
    CHARACTER_BRANCH_CHAPTER_STATUS_READY,
    CHARACTER_BRANCH_CHAPTER_STATUS_FAILED,
    CHARACTER_BRANCH_CHAPTER_STATUS_REVIEW,
)

CHARACTER_BRANCH_DEFAULT_STATUS = CHARACTER_BRANCH_STATUS_PENDING
CHARACTER_BRANCH_DEFAULT_CHAPTER_COUNT = 1
CHARACTER_BRANCH_MAX_CHAPTER_COUNT = 20
CHARACTER_BRANCH_MAX_GENERATION_BATCH = 5
CHARACTER_BRANCH_MAX_TITLE_LENGTH = 255
CHARACTER_BRANCH_SOURCE_PREFIX = "character_branch"
CHARACTER_BRANCH_STORYLINE_PREFIX = "branch"
CHARACTER_BRANCH_AUTO_DISCOVERY_ENABLED_DEFAULT = False
CHARACTER_BRANCH_AUTO_DISCOVERY_MIN_INACTIVE_CHAPTERS = 10
CHARACTER_BRANCH_AUTO_DISCOVERY_MAX_CANDIDATES = 20
CHARACTER_BRANCH_DEFAULT_WORD_COUNT = 3000
CHARACTER_BRANCH_ANCHOR_CONTEXT_MAX_CHARS = 24000
CHARACTER_BRANCH_MAINLINE_SUMMARY_MAX_CHARS = 12000
CHARACTER_BRANCH_DEFAULT_TITLE_TEMPLATE = "{character_name}支线"
CHARACTER_BRANCH_DEFAULT_SOURCE_REF_TEMPLATE = "character_branch:{branch_id}:chapter:{chapter_index}"
CHARACTER_BRANCH_VECTOR_COLLECTION_PREFIX = "character_branch_"
CHARACTER_BRANCH_VECTOR_SOURCE = "character_branch"
CHARACTER_BRANCH_VECTOR_ITEM_ID_TEMPLATE = "branch:{branch_id}:chapter:{chapter_index}"
