"""Core novel, job, chapter, and API constants."""

JOB_TYPE_GENERATE: str = "generate"
JOB_TYPE_CHARACTER_BRANCH: str = "character_branch"
JOB_TYPE_POST_PROCESSING: str = "post_processing"

DEFAULT_CHAPTER_INDEX: int = 1
DEFAULT_WORD_COUNT_PER_CHAPTER: int = 3000
DEFAULT_TARGET_CHAPTERS: int = 100
DEFAULT_OPTIMIZE_INTERVAL: int = 10
DEFAULT_BATCH_SIZE: int = 1

NOVEL_TYPE_PROJECT: str = "project"
NOVEL_MODE_STEP: str = "step"
NOVEL_MODE_AUTO: str = "auto"

AGENT_NAME_CLASSIFIER: str = "classifier"

PREVIOUS_CHAPTER_ENDING_CHARS: int = 500
OUTLINE_SOURCE_EDITOR: str = "editor"
REVIEW_FLAG_TYPE_FORCE_CORRECTED: str = "force_corrected"
REVIEW_FLAG_SEVERITY_WARNING: str = "warning"

EDITOR_DECISION_REWRITE: str = "rewrite"
EDITOR_DECISION_REVISE: str = "revise"
EDITOR_DECISION_PROCEED: str = "proceed"
EDITOR_MIN_PASS_SCORE: int = 70
EDITOR_MAX_REWRITES_FALLBACK: int = 3
EDITOR_DEFAULT_SCORE: int = 100

PREVIOUS_CHAPTER_ENDING_CHARS_FOR_CONTEXT: int = 3500
SUCCEEDING_CHAPTER_BEGINNING_CHARS: int = 1500
CHAPTER_SUMMARY_PREVIEW_CHARS: int = 150
MAX_ISSUE_SUMMARIES_IN_CONTEXT: int = 10
SHORT_TERM_MEMORY_WINDOW: int = 5
SHORT_MANUSCRIPT_CONTEXT_MAX_CHARS: int = 60_000

ORPHANED_JOB_STALE_SECONDS: int = 90
DEFAULT_WATCHDOG_TIMEOUT_SECONDS: int = 45

CHAPTER_TITLE_TEMPLATE: str = "第{}章"
CHAPTER_VERSION_DIR_TEMPLATE: str = "chapter_{:03d}"

API_STATUS_OK: str = "ok"
API_STATUS_SUCCESS: str = "success"
API_STATUS_DELETED: str = "deleted"

ISSUE_SIMILARITY_THRESHOLD: float = 0.45
OPTIMIZED_ISSUE_SUMMARY_PREFIX: str = "[已优化]"
