"""Vector store and embedding constants."""

AGENT_NAME_EMBEDDING: str = "embedding"

VECTOR_COLLECTION_PREFIX: str = "project_"
VECTOR_SOURCE_SETTING: str = "setting"
VECTOR_SOURCE_CHAPTER_EXTRACT: str = "chapter_extract"
VECTOR_SOURCE_SCENE_BLOCK: str = "scene_block"
VECTOR_SCENE_BLOCK_ITEM_ID_TEMPLATE: str = "scene_{project_id}_{scope_type}_{scope_key}"
VECTOR_TYPE_CHARACTER_STATE: str = "character_state"
VECTOR_SETTING_CHARACTER_ID_TEMPLATE: str = "setting_character_{name}"
VECTOR_CHAPTER_ITEM_ID_TEMPLATE: str = "{chapter_index}_{item_type}_{name}"
VECTOR_UNKNOWN_ITEM_TYPE: str = "unknown"
VECTOR_UNKNOWN_CHAPTER_INDEX: int = 0
VECTOR_RETRIEVE_N_RESULTS: int = 5

VECTOR_CHAPTER_EXTRACTS_N_RESULTS: int = 6
VECTOR_CHARACTER_QUERY_N_RESULTS: int = 3
VECTOR_WORLD_RULES_N_RESULTS: int = 8
VECTOR_FORESHADOWING_N_RESULTS: int = 8
VECTOR_PLOT_THREADS_N_RESULTS: int = 5
VECTOR_FALLBACK_LIST_SIZE: int = 8
VECTOR_ACTIVE_CONTEXT_RECENT_CHAPTER_WINDOW: int = 24
VECTOR_DUE_FORESHADOWING_LIMIT: int = 3
