"""Vector store and embedding constants."""

AGENT_NAME_EMBEDDING: str = "embedding"
TOKENS_PER_MILLION: float = 1_000_000.0
ALL_MODELS_LABEL: str = "All Models"

VECTOR_COLLECTION_PREFIX: str = "project_"
VECTOR_SOURCE_SETTING: str = "setting"
VECTOR_SOURCE_CHAPTER_EXTRACT: str = "chapter_extract"
VECTOR_RETRIEVE_N_RESULTS: int = 5
VECTOR_QUERY_TEXT_MAX_CHARS: int = 2000
VECTOR_OUTBOX_BATCH_SIZE: int = 10
DEFAULT_VECTOR_OUTBOX_MAX_RETRIES: int = 3

EMBEDDING_TIMEOUT_SECONDS: int = 120

VECTOR_CHAPTER_EXTRACTS_N_RESULTS: int = 6
VECTOR_CHARACTER_QUERY_N_RESULTS: int = 3
VECTOR_WORLD_RULES_N_RESULTS: int = 8
VECTOR_FORESHADOWING_N_RESULTS: int = 8
VECTOR_PLOT_THREADS_N_RESULTS: int = 5
VECTOR_FALLBACK_LIST_SIZE: int = 8
VECTOR_ACTIVE_CONTEXT_RECENT_CHAPTER_WINDOW: int = 24
VECTOR_DUE_FORESHADOWING_LIMIT: int = 3
